"""
Generates a standard set of SQL query templates for data profiling.
"""

HEADER_COMMENT = "-- Generated by CSV Profiler: A standard set of queries for data exploration."
SEPARATOR = "----------------"

# A static list of query templates, grouped by purpose.
# Placeholders like {column_name} are intended to be in the final output for manual editing.
QUERY_GROUPS = [
    {
        "title": "-- 🔹 Basic Exploration",
        "templates": [
            "SELECT * FROM {table_name};",
            "SELECT COUNT(*) AS total_rows FROM {table_name};",
            "SELECT * FROM {table_name} LIMIT 10;",
        ]
    },
    {
        "title": "-- 🔹 Column-Level Checks",
        "templates": [
            "SELECT DISTINCT {column_name} FROM {table_name};",
            "SELECT COUNT(DISTINCT {column_name}) AS unique_count FROM {table_name};",
            "SELECT COUNT(*) AS null_count FROM {table_name} WHERE {column_name} IS NULL;",
            "SELECT COUNT(*) AS blank_count FROM {table_name} WHERE TRIM({column_name}) = '';",
        ]
    },
    {
        "title": "-- 🔹 Data Profiling",
        "templates": [
            "SELECT MIN({column_name}) AS min_val, MAX({column_name}) AS max_val FROM {table_name};",
            "SELECT AVG({column_name}) AS avg_val, STDDEV({column_name}) AS std_val, SUM({column_name}) AS total_val FROM {table_name};",
            "SELECT {column_name}, COUNT(*) AS freq FROM {table_name} GROUP BY {column_name} ORDER BY freq DESC;",
        ]
    },
    {
        "title": "-- 🔹 Data Quality / Integrity",
        "templates": [
            "SELECT {column_name}, COUNT(*) AS dup_count FROM {table_name} GROUP BY {column_name} HAVING COUNT(*) > 1;",
            "SELECT COUNT(*) AS total_rows, COUNT(DISTINCT col1, col2) AS unique_rows FROM {table_name};",
            "SELECT t1.col, COUNT(*) FROM {table_name} t1 LEFT JOIN table2 t2 ON t1.col = t2.col WHERE t2.col IS NULL GROUP BY t1.col;",
        ]
    },
    {
        "title": "-- 🔹 Sampling & Debugging",
        "templates": [
            "SELECT * FROM {table_name} ORDER BY RANDOM() LIMIT 10;",
            "SELECT * FROM {table_name} ORDER BY {column_name} DESC LIMIT 5;",
        ]
    }
]

def generate_queries(table_name: str) -> str:
    """
    Generates a structured string of SQL query templates.

    Args:
        table_name: The name of the table to insert into the templates.

    Returns:
        A string containing the formatted query templates.
    """
    if not table_name:
        table_name = "your_table_name"

    # Build the final script part by part
    final_script_parts = [HEADER_COMMENT]

    first_group = True
    for group in QUERY_GROUPS:
        # Add separator before each group except the first one
        if not first_group:
            final_script_parts.append(SEPARATOR)
        first_group = False

        final_script_parts.append(group['title'])

        for template in group['templates']:
            # Only format the table_name, leaving other placeholders untouched
            final_script_parts.append(template.replace("{table_name}", table_name))

    return "\n".join(final_script_parts)